apiVersion: v1
kind: Namespace
metadata:
  name: k8s-papivot-tools
  labels:
    name: k8s-papivot-tools
    app: k8s-papivot-tools
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-papivot-tools-sa
  namespace: k8s-papivot-tools
  labels:
    name: k8s-papivot-tools
    app: k8s-papivot-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-papivot-tools-cr
  labels:
    app: k8s-papivot-tools
    name: k8s-papivot-tools
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs: ["get", "list", "watch"]
  - nonResourceURLs:
    - '*'
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-papivot-tools-crb
  labels:
    app: k8s-papivot-tools
    name: k8s-papivot-tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-papivot-tools-cr
subjects:
- kind: ServiceAccount
  name: k8s-papivot-tools-sa
  namespace: k8s-papivot-tools
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-papivot-tools
    name: k8s-papivot-tools
  name: k8s-papivot-tools-svc
  namespace: k8s-papivot-tools
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: k8s-papivot-tools
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: k8s-papivot-tools
    app: k8s-papivot-tools
  name: k8s-papivot-tools-deployment
  namespace: k8s-papivot-tools
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: k8s-papivot-tools
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-papivot-tools
        version: v1
    spec:
      containers:
      - env:
        - name: INCLUSTER_CONFIG
          value: "1"
        - name: CLUSTER_NAME
          value: "clustername.demo.local"
        image: whoami6443/k8sapiwalkthru:0.0.3
        imagePullPolicy: Always
        name: k8s-papivot-tools
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          runAsUser: 9999
        volumeMounts:
        - mountPath: /user/k8soper
          name: cache-volume
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        stdin: true
        tty: true
      volumes:
      - name: cache-volume
        emptyDir: {}
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: k8s-papivot-tools-sa
      serviceAccountName: k8s-papivot-tools-sa
      terminationGracePeriodSeconds: 30
