---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-obj-dump-tls-cert
  namespace: k8s-papivot-tools
spec:
  commonName: prometheus
  dnsNames:
  - k8s-obj.k8s.lab.test
  duration: 87600h0m0s
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: k8s-obj-ca-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  renewBefore: 360h0m0s
  secretName: k8s-obj-dump-tls
  subject:
    organizations:
    - Project K8s tools
  usages:
  - server auth
  - client auth
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-obj-dump
    name: k8s-obj-dump
  name: k8s-obj-dump-svc
  namespace: k8s-papivot-tools
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: k8s-obj-dump
  type: ClusterIP
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: k8s-obj-dump
    name: k8s-obj-dump
  name: k8s-obj-dump-httpproxy
  namespace: k8s-papivot-tools
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: k8s-obj-dump-svc
      port: 80
  virtualhost:
    fqdn: k8s-obj.k8s.lab.test
#    tls:
#      secretName: k8s-obj-dump-tls