---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-obj-dump
    name: k8s-obj-dump
  name: k8s-obj-dump-svc
  namespace: k8s-papivot-tools
  annotations:
    external-dns.alpha.kubernetes.io/hostname: k8s-obj.k8s.lab.test
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: k8s-obj-dump
  type: LoadBalancer