---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-obj-dump
    name: k8s-obj-dump
  name: k8s-obj-dump-svc
  namespace: k8s-papivot-tools
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: k8s-obj-dump
  type: LoadBalancer